#include "board_api.h"
#include "i2c.h"
#include "i2c_driver.h"
#include "gpio.h"
#include "stm32l5xx_hal.h"

/* I2C1: external connector — SCL = PB8, SDA = PB9 */
#define I2C1_SCL_PIN  GPIO_PIN_ENCODE(1, 8)
#define I2C1_SDA_PIN  GPIO_PIN_ENCODE(1, 9)

/*
 * I2C timing register values for PCLK1 = 110 MHz.
 * Generated by the STM32 I2C timing tool (AN4235) or STM32CubeMX.
 * Must be regenerated if the system clock changes.
 *
 * TIMINGR layout: [31:28] PRESC | [23:20] SCLDEL | [19:16] SDADEL
 *                 [15:8]  SCLH  | [7:0]   SCLL
 *
 * t_presc = (PRESC+1) / PCLK1
 * SCL period ≈ (SCLL+1 + SCLH+1) × t_presc  (plus internal sync delays)
 *
 * Standard (100 kHz): PRESC=1 → t_presc=18.18 ns
 *   SCLL=0xCE(206), SCLH=0x9C(156) → (207+157)×18.18 ns ≈ 6620 ns
 *   + sync delays ≈ 10 μs ≈ 100 kHz
 *
 * Fast (400 kHz): PRESC=0 → t_presc=9.09 ns
 *   SCLL=0x91(145), SCLH=0x29(41) → (146+42)×9.09 ns ≈ 1709 ns
 *   + sync delays ≈ 2.5 μs ≈ 400 kHz
 *
 * Fast-plus (1 MHz): PRESC=0 → t_presc=9.09 ns
 *   SCLL=0x38(56), SCLH=0x0F(15) → (57+16)×9.09 ns ≈ 663 ns
 *   + sync delays ≈ 1 μs ≈ 1 MHz
 */
#define I2C_TIMING_STANDARD   0x10909CECU  /* 100 kHz */
#define I2C_TIMING_FAST       0x00702991U  /* 400 kHz */
#define I2C_TIMING_FAST_PLUS  0x00300F38U  /* 1 MHz   */

static I2C_HandleTypeDef hi2c1;

static i2c_t i2c1_drv = {
    .hal     = &hi2c1,
    .name    = "i2c1",
    .scl_pin = I2C1_SCL_PIN,
    .sda_pin = I2C1_SDA_PIN,
};

/* ------------------------------------------------------------------ */
/* Slave pool                                                           */
/* ------------------------------------------------------------------ */

#define BOARD_I2C_MAX_SLAVES 8
static struct i2c_slave slave_pool[BOARD_I2C_MAX_SLAVES];
static int slave_count;

/* ------------------------------------------------------------------ */
/* Bus ops — ctx is always i2c_t *                                     */
/* ------------------------------------------------------------------ */

static int board_i2c_open(void *ctx)
{
    (void)ctx;
    return 0;
}

static int board_i2c_close(void *ctx)
{
    (void)ctx;
    return 0;
}

static int board_i2c_transfer_one(void *ctx, uint16_t addr, i2c_dir_t dir,
        uint8_t *buf, uint16_t len, i2c_xfer_opt_t opt)
{
    return i2c_drv_transfer_one((i2c_t *)ctx, addr, dir, buf, len, opt);
}

static int board_i2c_transfer_one_it(void *ctx, uint16_t addr, i2c_dir_t dir,
        uint8_t *buf, uint16_t len, i2c_xfer_opt_t opt,
        uint8_t use_dma, i2c_cb_t cb, void *cb_ctx)
{
    return i2c_drv_transfer_one_it((i2c_t *)ctx, addr, dir, buf, len, opt, use_dma, cb, cb_ctx);
}

static int board_i2c_apply_config(void *ctx, i2c_speed_t speed, i2c_addr_mode_t addr_mode)
{
    i2c_t *dev = (i2c_t *)ctx;
    I2C_HandleTypeDef *h = (I2C_HandleTypeDef *)dev->hal;

    uint32_t timing = I2C_TIMING_STANDARD;
    switch (speed) {
        case I2C_SPEED_FAST:      timing = I2C_TIMING_FAST;      break;
        case I2C_SPEED_FAST_PLUS: timing = I2C_TIMING_FAST_PLUS; break;
    }

    i2c_drv_deinit(dev);
    h->Init.Timing         = timing;
    h->Init.AddressingMode = (addr_mode == I2C_ADDR_10BIT) ?
        I2C_ADDRESSINGMODE_10BIT : I2C_ADDRESSINGMODE_7BIT;
    i2c_drv_init(dev);
    return 0;
}

static int board_i2c_recover(void *ctx, uint32_t error_flags)
{
    (void)error_flags;
    i2c_drv_abort((i2c_t *)ctx);
    return 0;
}

/*
 * board_i2c_bus_recover — GPIO bit-bang 9-clock recovery.
 *
 * Generates 9 SCL pulses with SDA high, then a STOP condition.
 * A slave stuck mid-transfer will clock out remaining bits and release SDA.
 * Restores I2C peripheral via i2c_drv_init() → HAL_I2C_Init() → MspInit().
 */
static int board_i2c_bus_recover(void *ctx)
{
    i2c_t *dev = (i2c_t *)ctx;

    i2c_drv_deinit(dev);

    /* Configure SCL and SDA as open-drain outputs for bit-bang recovery */
    gpio_init(dev->scl_pin, GPIO_MODE_OUTPUT_OD, GPIO_PULL_UP, GPIO_SPEED_HIGH);
    gpio_init(dev->sda_pin, GPIO_MODE_OUTPUT_OD, GPIO_PULL_UP, GPIO_SPEED_HIGH);

    gpio_write(dev->sda_pin, GPIO_HIGH);
    gpio_write(dev->scl_pin, GPIO_HIGH);

    /* 9 clock pulses */
    for (int i = 0; i < 9; i++) {
        gpio_write(dev->scl_pin, GPIO_LOW);
        for (volatile int d = 0; d < 100; d++) __asm volatile("nop");
        gpio_write(dev->scl_pin, GPIO_HIGH);
        for (volatile int d = 0; d < 100; d++) __asm volatile("nop");

        /* If SDA is released, the stuck slave has recovered */
        if (gpio_read(dev->sda_pin) == GPIO_HIGH) break;
    }

    /* STOP condition: SDA low then high while SCL high */
    gpio_write(dev->sda_pin, GPIO_LOW);
    for (volatile int d = 0; d < 100; d++) __asm volatile("nop");
    gpio_write(dev->scl_pin, GPIO_HIGH);
    for (volatile int d = 0; d < 100; d++) __asm volatile("nop");
    gpio_write(dev->sda_pin, GPIO_HIGH);

    /* Reinit restores GPIO to AF mode via MspInit */
    return i2c_drv_init(dev);
}

static const struct i2c_bus_ops i2c_ops = {
    .open            = board_i2c_open,
    .close           = board_i2c_close,
    .transfer_one    = board_i2c_transfer_one,
    .transfer_one_it = board_i2c_transfer_one_it,
    .apply_config    = board_i2c_apply_config,
    .recover         = board_i2c_recover,
    .bus_recover     = board_i2c_bus_recover,
};

static struct i2c_bus i2c1_bus = { .name = "i2c1", .ops = &i2c_ops, .ctx = &i2c1_drv };

/* ------------------------------------------------------------------ */
/* IRQ handlers                                                         */
/* ------------------------------------------------------------------ */

void I2C1_EV_IRQHandler(void) { HAL_I2C_EV_IRQHandler(&hi2c1); }
void I2C1_ER_IRQHandler(void) { HAL_I2C_ER_IRQHandler(&hi2c1); }

/* ------------------------------------------------------------------ */
/* Init                                                                 */
/* ------------------------------------------------------------------ */

void board_i2c_init(void)
{
    hi2c1.Instance              = I2C1;
    hi2c1.Init.Timing           = I2C_TIMING_STANDARD;
    hi2c1.Init.OwnAddress1      = 0;
    hi2c1.Init.AddressingMode   = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode  = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.OwnAddress2      = 0;
    hi2c1.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
    hi2c1.Init.GeneralCallMode  = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode    = I2C_NOSTRETCH_DISABLE;

    i2c_drv_init(&i2c1_drv);
    i2c_bus_register(&i2c1_bus);
}

int board_i2c_add_slave(const char *bus_name, const char *name,
        uint16_t addr, i2c_addr_mode_t addr_mode, i2c_speed_t speed)
{
    if (!bus_name || !name || slave_count >= BOARD_I2C_MAX_SLAVES) return -1;
    if (addr_mode != I2C_ADDR_7BIT && addr_mode != I2C_ADDR_10BIT) return -1;
    if (speed != I2C_SPEED_STANDARD && speed != I2C_SPEED_FAST && speed != I2C_SPEED_FAST_PLUS) return -1;

    struct i2c_slave *s = &slave_pool[slave_count];
    s->name      = name;
    s->bus_name  = bus_name;
    s->addr      = addr;
    s->addr_mode = addr_mode;
    s->speed     = speed;

    int rc = i2c_slave_register(s);
    if (rc == 0) slave_count++;

    return rc;
}
